from django.shortcuts import render


def home(request):

    recipes = [
        {
            "title": "Grilled Chicken Salad",
            "description": "Fresh vegetables with juicy grilled chicken breast.",
            "category": "Healthy",
            "rating": 4.9,
            "review_count": 250,
            "time": "25 min",
            "calories": 320,
            "difficulty": "Easy",
            "chef": "John Smith",
            "chef_image": "https://i.pravatar.cc/100?img=11",
            "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
        },
        {
            "title": "Italian Pasta",
            "description": "Creamy white sauce pasta with fresh herbs.",
            "category": "Italian",
            "rating": 4.8,
            "review_count": 198,
            "time": "35 min",
            "calories": 540,
            "difficulty": "Medium",
            "chef": "Emma Watson",
            "chef_image": "https://i.pravatar.cc/100?img=22",
            "image": "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9",
        },
        {
            "title": "Protein Bowl",
            "description": "High protein meal packed with lean protein and veggies.",
            "category": "Fitness",
            "rating": 4.7,
            "review_count": 143,
            "time": "20 min",
            "calories": 410,
            "difficulty": "Easy",
            "chef": "Alex Morgan",
            "chef_image": "https://i.pravatar.cc/100?img=33",
            "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
        },
        {
            "title": "Chocolate Pancake",
            "description": "Soft fluffy pancakes topped with rich chocolate syrup.",
            "category": "Dessert",
            "rating": 4.9,
            "review_count": 401,
            "time": "18 min",
            "calories": 610,
            "difficulty": "Easy",
            "chef": "Sophia",
            "chef_image": "https://i.pravatar.cc/100?img=44",
            "image": "https://images.unsplash.com/photo-1528207776546-365bb710ee93",
        },
        {
            "title": "Classic Margherita Pizza",
            "description": "Crispy homemade pizza with mozzarella, basil and tomato sauce.",
            "category": "Pizza",
            "rating": 4.8,
            "review_count": 325,
            "time": "40 min",
            "calories": 680,
            "difficulty": "Medium",
            "chef": "Marco Rossi",
            "chef_image": "https://i.pravatar.cc/100?img=55",
            "image": "https://images.unsplash.com/photo-1513104890138-7c749659a591",
        },
        {
            "title": "Avocado Toast",
            "description": "Whole grain toast topped with avocado, eggs and fresh herbs.",
            "category": "Breakfast",
            "rating": 4.6,
            "review_count": 187,
            "time": "15 min",
            "calories": 290,
            "difficulty": "Easy",
            "chef": "Olivia Brown",
            "chef_image": "https://i.pravatar.cc/100?img=66",
            "image": "https://images.unsplash.com/photo-1525351484163-7529414344d8",
        },
    ]

    return render(request, "home.html", {"recipes": recipes})
