# Generated by Django 6.0.7 on 2026-08-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
